# Generated by Django 2.1.4 on 2018-12-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponame', models.CharField(help_text='slug', max_length=70, unique=True)),
                ('name', models.SlugField()),
                ('owner', models.SlugField()),
                ('hasTopicTag', models.BooleanField(default=None)),
                ('hasDocumentation', models.BooleanField(default=None)),
                ('hasDescription', models.BooleanField(default=None)),
                ('hasLicense', models.BooleanField(default=None)),
                ('hasContributingGuidelines', models.BooleanField(default=None)),
                ('commitCount', models.IntegerField(blank=True, null=True)),
                ('prCount', models.IntegerField(blank=True, null=True)),
                ('prMergedCount', models.IntegerField(blank=True, null=True)),
                ('issueCount', models.IntegerField(blank=True, null=True)),
                ('branchCount', models.IntegerField(blank=True, null=True)),
                ('maintainersCount', models.IntegerField(blank=True, null=True)),
                ('avgIssueResolutionTime', models.DurationField(blank=True, null=True)),
                ('avgPRmergeTime', models.DurationField(blank=True, null=True)),
                ('avgFirstResponseTime', models.DurationField(blank=True, null=True)),
                ('weeklyContributorsCount', models.IntegerField(blank=True, null=True)),
                ('firstTimeContributorsThisWeek', models.IntegerField(blank=True, null=True)),
                ('weeklyContributorsChange', models.IntegerField(blank=True, null=True)),
                ('contributorsList', models.TextField(blank=True, null=True)),
                ('contributorsThisWeekList', models.TextField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('baseScore', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('activityScore', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('popularityScore', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('inclusivityScore', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('meritScore', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Repository',
                'verbose_name_plural': 'Repositories',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text='slug', unique=True)),
                ('full_name', models.CharField(blank=True, max_length=50)),
                ('icon', models.URLField(blank=True)),
                ('short_description', models.CharField(blank=True, max_length=200)),
                ('related', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('url', models.URLField(blank=True)),
                ('wikipedia_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Topics',
                'verbose_name_plural': 'Topic',
            },
        ),
        migrations.AddField(
            model_name='repository',
            name='topics',
            field=models.ManyToManyField(related_name='repo_name', to='repo.Topic'),
        ),
    ]
